version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html
    overwrite: yes

permissions:
  - object: /var/www/html
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
